name: RunsafeMailbox
main: no.runsafe.mailbox.Plugin
version: 1.0.@BUILD@
author: Kruithne
description:
commands:
  viewmailbox:
    description: Views a players mailbox
  mail:
    description: Allows you to send mail to another player
